bot:
  token: Njg1MjQ5MDM2OTk0NzQwMjQy.XofHAg.5KCA1IDVl_SmAXSRU_sbmPTyDlc
  rating-channel-id: 706585065815015487

host: localhost

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${host:localhost}:3306/civilization_rating_database
    username: civilizationBot
    password: 1234567890

discord:
  administrator:
    name: gigasvin323