bot:
  token: Njk4NjAyOTYwMDc4MzcyOTM0.XpIOtQ.MgK5-V2RP_AiKZaD5FhHP5-nqJE


host: localhost

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://${host:localhost}:3306/civilization_rating_database?serverTimezone=UTC
    username: civilizationBot
    password: 123456789

discord:
  administrator:
    name: gigasvin323
    role:
      name: админ
  channel:
    notification:
      name: notification
    rating-games:
#      TODO: split by twp channels
      name: рейтинговые-игры, рейтинговые-отчеты
#      TODO: update for different discords
      channel-id: 692408363178524673
    rating:
      channel-id: 706585065815015487
